"""fix column

Revision ID: 1d81ee9ac393
Revises: 0ffa9d7777ed
Create Date: 2025-02-04 18:41:01.401876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d81ee9ac393"
down_revision: Union[str, None] = "0ffa9d7777ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants", sa.Column("discord_user_id", sa.BigInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "discord_user_id")
    # ### end Alembic commands ###
