"""fix column

Revision ID: 0ffa9d7777ed
Revises: b59a7c793259
Create Date: 2025-02-04 14:18:31.533651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffa9d7777ed'
down_revision: Union[str, None] = 'b59a7c793259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE groups ALTER COLUMN is_disabled TYPE boolean USING CASE WHEN is_disabled=0 THEN false ELSE true END')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE groups ALTER COLUMN is_disabled TYPE integer USING CASE WHEN is_disabled THEN 1 ELSE 0 END')
    # ### end Alembic commands ###
