"""fix log table

Revision ID: 78676a84a845
Revises: 1d81ee9ac393
Create Date: 2025-02-08 23:59:22.635738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78676a84a845'
down_revision: Union[str, None] = '1d81ee9ac393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_chat_logs', sa.Column('team_id', sa.String(length=255), nullable=False))
    op.drop_column('text_chat_logs', 'user_id')
    op.add_column('voice_chat_logs', sa.Column('team_id', sa.String(length=255), nullable=False))
    op.drop_column('voice_chat_logs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_chat_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('voice_chat_logs', 'team_id')
    op.add_column('text_chat_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('text_chat_logs', 'team_id')
    # ### end Alembic commands ###
